Feature/pers 99
kanselarij-vlaanderen/press-releases-publication-tasks-generator-service pull request #1
Opened 2021-08-02 07:21 UTC by MiVvlt

2021-08-02 08:49 UTC, erikap requested changes
De core van deze service is zeker OK en de SPARQL queries ook correct :+1: 

Algemeen idee van de feedback:  
- SPARQL queries zoveel mogelijk baseren op URI ipv op UUID als je de URI ter beschikking hebt
- het uitvoeren van queries en parsen van het result toevoegen in `helpers/press-release-sparql-queries` zodanig dat `app.js` zo eenvoudig mogelijk blijft. Hierdoor kunnen developers in een oogopslag zien wat de microservice doet door naar `app.js` te kijken zonder in de details te moeten duiken.

Verder ook nog een README toevoegen met minstens documentatie over:
- hoe de service toegevoegd kan worden in een application stack (vb. https://github.com/kanselarij-vlaanderen/themis-export-service#getting-started)
- de endpoints die de service aanbiedt (vb. https://github.com/kanselarij-vlaanderen/themis-export-service#reference)
- het data model dat de service gebruikt: wat verwacht hij te vinden in de triplestore en wat wordt er geinsert. (vb. https://github.com/kanselarij-vlaanderen/themis-publication-consumer#model)

2021-08-02 08:49 UTC, erikap commented on app.js
> +import {isNotNullOrUndefined} from "./helpers/util";
Consistentie in quotes. Andere import statements gebruiken single quote.

2021-08-02 08:49 UTC, erikap commented on app.js
> +} from './helpers/press-release-sparql-queries'
`;` ontbreekt

2021-08-02 08:49 UTC, erikap commented on app.js
> +	// en bijhorend publication event (ebucore:PublicationEvent) opgezocht in de triplestore.
Inline code comments kunnen best in Engels geschreven worden.

2021-08-02 08:49 UTC, erikap commented on app.js
> +		return;
Voor deze cases heeft de mu-javascript-template [error handling middleware](https://github.com/mu-semtech/mu-javascript-template#imports) zodanig dat een JSON:API compliant response teruggegeven wordt. 

Voorbeeld van het gebruik: 
- https://github.com/lblod/import-with-sameas-service/blob/master/app.js#L47
- https://github.com/lblod/import-with-sameas-service/blob/master/app.js#L59

De status code kan ingesteld worden via `err.status = 500`.

Deze comment geldt ook voor de andere catch blocks.

2021-08-02 08:49 UTC, erikap commented on app.js
> +	}
Mag verwijderd worden of uit comments gehaald?

2021-08-02 08:49 UTC, erikap commented on app.js
> +		started = queryResult.results.bindings[0].started ? queryResult.results.bindings[0].started.value : undefined;
Het uitvoeren van de query en de parsing van het resultaat zou ik eerder in `findPressReleasesWithPublicationEvents` zodanig dat deze method ofwel `null` teruggeeft indien er geen resultaat gevonden wordt ofwel een JS object met properties `graph`, `publicationEvent`, ...
Op die manier staan de variabel names uit het `SELECT` statement en de parsing van het resultaat bij elkaar, wat het makkelijker maintainbaar maakt op termijn.

2021-08-02 08:49 UTC, erikap commented on app.js
> +	if (isNotNullOrUndefined(plannedStartDate) && new Date(plannedStartDate) > new Date()) {
Het nut van de `isNotNullOrUndefined` util zie ik niet helemaal. Gewoon `plannedStartDate != null` leest toch eenvoudiger in JS?

2021-08-02 08:49 UTC, erikap commented on app.js
> +			await query(removeFuturePublicationDate(graph, pressReleaseUUID));
Dit is niet incorrect, maar gegeven dat je de URI van het persbericht hier al hebt  (uit die eerst `SELECT`-query) is het beter om de delete-query te baseren op de URI ipv op de UUID. Dat maakt de query ook iets eenvoudiger.

Ook hier zou ik het uitvoeren van de query toevoegen in `removeFuturePublicationDate()`. De method name impliceert immers eerder dat de actie uitgevoerd zal worden dan dat er een string gereturned zal worden.

2021-08-02 08:49 UTC, erikap commented on app.js
> +		await query(setPublicationStartDateTimeAndPublishedStartDateTime(graph, pressReleaseUUID, currentDate));
Zelfde comment als hierboven: best baseren op persbericht URI en query uitvoeren in de method zelf.

2021-08-02 08:49 UTC, erikap commented on app.js
> +	const publicationChannelsQuery = await query(getPublicationChannelsByPressReleaseUUID(graph, pressReleaseUUID));
Zelfde comment als hierboven: best baseren op persbericht URI en query uitvoeren in de method zelf.
De method kan dan ook best een array van strings (publication channel URIs) teruggeven of een lege array indien er geen publication channels zijn.

2021-08-02 08:49 UTC, erikap commented on app.js
> +	return await Promise.all(promises)
Volledig correct wat je hier doet, maar de ervaring met Virtuoso heeft ons al geleerd dat die meerdere queries in parallel niet zo fijn vindt. Je kan deze queries dus toch best serieel uitvoeren in een `for`-loop.

2021-08-02 08:49 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +					OPTIONAL { ?publicationEvent 	ebucore:hasChannelPublicationEvent 			?publicationChannels }
Aangezien `publicationChannels` uit het resultaat niet gebruikt wordt, kan dit best verwijderd worden uit deze query.

2021-08-02 08:49 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +						    	prov:generated					${sparqlEscapeUri(publicationEvent)};
Deze relatie moet omgekeerd gelegd worden:  `<publication-event> prov:generated <publication-task>`

2021-08-02 08:49 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +						    	mu:uuid 						${sparqlEscapeString(uuid())}  .
Aangezien hier nog eens `uuid()` aangeroepen wordt, gaat dit een andere uuid zijn dan die dat gebruikt wordt in de URI. An sich niet incorrect, maar doorgaans gebruiken we hier dezelfde uuid voor.

2021-08-02 10:23 UTC, MiVvlt commented on app.js
> +	if (isNotNullOrUndefined(plannedStartDate) && new Date(plannedStartDate) > new Date()) {
ja dat is een gewoonte, in 1 of andere angular library is die beschikbaar en dit leest iets vlotter voor mij. maar indien nodig haal ik die er wel uit.

2021-08-02 17:07 UTC, erikap requested changes
Kan je je editor zo configureren, om conflicts in de toekomst te vermijden, zodanig dat:
- met spaties ipv tabs gewerkt wordt 
- trailing whitespaces verwijderd worden

README ontbreekt nog steeds (zie vorige review comment)

2021-08-02 17:07 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +	}
Lijkt mij overbodig?  (komt nog een aantal keer voor)

2021-08-02 17:07 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +export function setPublicationStartDateTimeAndPublishedStartDateTime(graph, pressRelease, dateTime) {
`startPublication()` is misschien een duidelijkere (en kortere) method name?

2021-08-02 17:07 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +				${sparqlEscapeUri(pressRelease)}		ext:publicationChannels 	?pubChannel .
Bij de eerste review over het hoofd gezien. Hier moet je de publication-channels nemen die gelinkt zijn aan het publication-event (dat op zijn beurt gelinkt is aan het persbericht)

2021-08-02 17:07 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +			${sparqlEscapeUri(publicationEvent)} 	prov:generated		vlpt:${newId} .xz
Die `xz` hoort hier waarschijnlijk niet thuis...

2021-08-02 17:07 UTC, erikap commented on helpers/util.js
> +}
Ik zie het nut van zo'n util in sommige programmeertalen, maar in javascript ontgaat het mij wat. Als je het leesbaarder vindt, ga ik er ook niet over vallen, maar de inverse ook nog eens expliciet als methode maken voelt mij als developer wel heel vreemd aan.

2021-08-02 17:10 UTC, erikap commented on app.js
> +	const publicationChannelsQuery = await query(getPublicationChannelsByPressReleaseUUID(graph, pressReleaseUUID));
Return type zijn hier nog steeds de query result bindings

2021-08-04 19:31 UTC, erikap commented
Hier staan nog enkele comments die resolved moeten worden.
Vooral deze https://github.com/kanselarij-vlaanderen/press-releases-publication-tasks-generator-service/pull/1#discussion_r681131503 is blocking om de PR door te laten.

2021-08-04 20:57 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +export async function findPressReleasesWithPublicationEvents(id) {
Aangezien dit maar 1 resultaat teruggeeft, is `findPressReleaseWithPublicationEvent` waarschijnlijk een betere naam

2021-08-04 23:30 UTC, MiVvlt commented
>     * at verwacht hij te vinden in de triplestore en wat wordt er geinsert



> De core van deze service is zeker OK en de SPARQL queries ook correct 👍
> 
> Algemeen idee van de feedback:
> 
>     * SPARQL queries zoveel mogelijk baseren op URI ipv op UUID als je de URI ter beschikking hebt
> 
>     * het uitvoeren van queries en parsen van het result toevoegen in `helpers/press-release-sparql-queries` zodanig dat `app.js` zo eenvoudig mogelijk blijft. Hierdoor kunnen developers in een oogopslag zien wat de microservice doet door naar `app.js` te kijken zonder in de details te moeten duiken.
> 
> 
> Verder ook nog een README toevoegen met minstens documentatie over:
> 
>     * hoe de service toegevoegd kan worden in een application stack (vb. https://github.com/kanselarij-vlaanderen/themis-export-service#getting-started)
> 
>     * de endpoints die de service aanbiedt (vb. https://github.com/kanselarij-vlaanderen/themis-export-service#reference)
> 
>     * het data model dat de service gebruikt: wat verwacht hij te vinden in de triplestore en wat wordt er geinsert. (vb. https://github.com/kanselarij-vlaanderen/themis-publication-consumer#model)

moeten hierbij de volledige models (press-release, publication-event, publication channel nog toegevoegd worden? of wat ontbreekt hier nog?

2021-08-05 19:19 UTC, erikap requested changes

2021-08-05 19:19 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +				?publicationEvent						ebucore:hasChannelPublicationEvent 	?pubChannel .
Deze triple moet in de omgekeerde richting

2021-08-05 19:19 UTC, erikap commented on helpers/press-release-sparql-queries.js
> +export async function findPressReleasesWithPublicationEvent(id) {
Aangezien dit maar 1 resultaat teruggeeft, is `findPressReleaseWithPublicationEvent` (enkelvoud) waarschijnlijk een betere naam

2021-08-05 19:21 UTC, erikap commented
> > ```
> > * at verwacht hij te vinden in de triplestore en wat wordt er geinsert
> > ```
> 
> 
> > De core van deze service is zeker OK en de SPARQL queries ook correct 👍
> > Algemeen idee van de feedback:
> > ```
> > * SPARQL queries zoveel mogelijk baseren op URI ipv op UUID als je de URI ter beschikking hebt
> > 
> > * het uitvoeren van queries en parsen van het result toevoegen in `helpers/press-release-sparql-queries` zodanig dat `app.js` zo eenvoudig mogelijk blijft. Hierdoor kunnen developers in een oogopslag zien wat de microservice doet door naar `app.js` te kijken zonder in de details te moeten duiken.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Verder ook nog een README toevoegen met minstens documentatie over:
> > ```
> > * hoe de service toegevoegd kan worden in een application stack (vb. https://github.com/kanselarij-vlaanderen/themis-export-service#getting-started)
> > 
> > * de endpoints die de service aanbiedt (vb. https://github.com/kanselarij-vlaanderen/themis-export-service#reference)
> > 
> > * het data model dat de service gebruikt: wat verwacht hij te vinden in de triplestore en wat wordt er geinsert. (vb. https://github.com/kanselarij-vlaanderen/themis-publication-consumer#model)
> > ```
> 
> 
> moeten hierbij de volledige models (press-release, publication-event, publication channel nog toegevoegd worden? of wat ontbreekt hier nog?

Voor het model is voldoende gedocumenteerd in de README. Het enige wat ontbreekt is hoe de service met een gebuilde Docker image toegevoegd kan worden aan de stack. Zie ook comment in Jira op PERS-99.

2021-08-06 08:55 UTC, closed without merging